  # control-hub/requirements.yaml
dependencies:
  - name: mysql
    version: 0.10.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
  - name: influxdb
    version: 0.11.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: influxdb.enabled