{{- range $app := .Values.apps }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" $ }}-{{ $app.name | replace "_" "-" }}"
  labels:
    app: {{ $app.name | quote }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ $app.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ $app.name | quote }}
        release: {{ $.Release.Name }}
    spec:
      initContainers:
      - name: init-mysql
        image: mysql
        env:
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ template "mysql.fullname" $ }}"
              key: mysql-root-password
        - name: DB_HOST
          value: "{{ template "mysql.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        command: ['sh', '-c', 'mysql -w --connect-timeout=5 -s -N -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASSWORD}" -e "SELECT USER()"']
      containers:
        - name: haveged
          image: "harbur/haveged:1.7c-1"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
        - name: {{ $app.name | replace "_" "-" }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 500
          env:
          {{- range $key, $val := $app.container.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          - name: INIT_SECURITY
            value: "true"
          - name: DPM_CONF_APPS_TO_START
            value: {{ $app.name }}
          {{- range $app := $.Values.apps }}
          - name: "DPM_CONF_DPM_APP_{{ $app.name | upper }}"
            # value: "{{ $.Values.appProto }}://{{ template "fullname" $ }}-{{ $app.name | replace "_" "-" }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.service.port }}/{{ $app.name }}"
            value: "{{ $.Values.appProto }}://{{ template "fullname" $ }}-{{ $app.name | replace "_" "-" }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.service.port }}"
          {{- end }}
          - name: DPM_CONF_DPM_BASE_URL
            value: "{{ $.Values.ingress.proto }}://{{ $.Values.ingress.host }}.{{ $.Values.ingress.domain }}"
          - name: DPM_CONF_HTTP_LOAD_BALANCER_URL
            value: "{{ $.Values.ingress.proto }}://{{ $.Values.ingress.host }}.{{ $.Values.ingress.domain }}"
          - name: DPM_CONF_DB_URL
            value: "{{ $.Values.influxdb.proto }}://{{ template "influxdb.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.influxdb.config.http.bind_address }}"
          - name: DPM_CONF_DB_NAME
            value: "dpm"
          - name: DPM_CONF_DB_USER
            value: {{ $.Values.schInfluxUser }}
          - name: DPM_CONF_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ template "fullname" $ }}"
                key: influxdb-password
          - name: DPM_CONF_DPM_APP_DB_URL
            value: "{{ $.Values.influxdb.proto }}://{{ template "influxdb.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.influxdb.config.http.bind_address }}"
          - name: DPM_CONF_DPM_APP_DB_NAME
            value: "dpm_app"
          - name: DPM_CONF_DPM_APP_DB_USER
            value: {{ $.Values.schInfluxUser }}
          - name: DPM_CONF_DPM_APP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ template "fullname" $ }}"
                key: influxdb-password
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "mysql.fullname" $ }}
                key: mysql-root-password
          - name: DB_HOST
            value: "{{ template "mysql.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local"
          - name: DB_PORT
            value: "3306"
          - name: DPM_ADMIN_APP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ template "fullname" $ }}"
                key: admin-password
          ports:
          - name: http
            containerPort: {{ $.Values.service.port }}
          - name: http-admin
            containerPort: {{ $.Values.service.adminPort }}
          livenessProbe:
            exec:
              command:
              - curl
              - -f
              - http://localhost:18631/public-rest/v1/health
            initialDelaySeconds: 180
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
              - curl
              - -f
              - http://localhost:18631/public-rest/v1/health
            initialDelaySeconds: 180
            timeoutSeconds: 1
          resources:
{{ toYaml $.Values.resources | indent 12 }}
    {{- if $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end }}